import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="fa" dir="rtl">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
        style={{ direction: "rtl", fontFamily: 'Vazirmatn, Arial, Helvetica, sans-serif' }}
      >
        <header className="w-full bg-primary/95 shadow-md sticky top-0 z-20 flex items-center justify-between px-8 py-4 mb-6 rounded-b-2xl">
          <div className="text-2xl font-extrabold text-secondary tracking-tight drop-shadow">کانون تبلیغاتی حنان</div>
          <nav className="flex gap-4">
            <a href="/auth/login" className="btn-secondary">ورود</a>
            <a href="/auth/register" className="btn-primary">ثبت‌نام</a>
          </nav>
        </header>
        {children}
      </body>
    </html>
  );
}
